### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by fabianbergmark** [LIFX/lifx-sdk-android#25] opened 2015-03-25 18:49 UTC
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: *, PID: 17927
    java.lang.NullPointerException: Attempt to invoke virtual method 'lifx.java.android.entities.internal.LFXSiteID lifx.java.android.entities.internal.LFXBinaryPath.getSiteID()' on a null object reference
            at lifx.java.android.entities.internal.LFXMessage.getMessageDataRepresentation(LFXMessage.java:487)
            at lifx.java.android.network_context.internal.transport_manager.gateway_connection.LFXUDPGatewayConnection.sendNextMessageFromOutbox(LFXUDPGatewayConnection.java:174)
            at lifx.java.android.network_context.internal.transport_manager.gateway_connection.LFXUDPGatewayConnection.access$000(LFXUDPGatewayConnection.java:32)
            at lifx.java.android.network_context.internal.transport_manager.gateway_connection.LFXUDPGatewayConnection$3.run(LFXUDPGatewayConnection.java:72)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5696)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by besherman** [comment] 2015-03-26 06:50
Which version did this occur in?

**Comment by fabianbergmark** [comment] 2015-03-26 09:51
android:versionCode="1"
android:versionName="0.5"

This is a real showstopper for us. The app randomly crashes after a while.

**Comment by Cakey123445** [comment] 2015-08-10 13:00
Have put a catch into my next update to stop the crash but won't fix the cause. Looks like a message is created without a path and passed to the inbox. Challenge is to find who/where put it in the outbox in LFXUDPGatewayConnection.java:sendNextMessageFromOutbox(),

**Comment by smarthall** [comment] 2015-08-18 06:48
Thanks @Cakey123445 for resolving this.

**Closed by smarthall** 2015-08-18 06:48 UTC
